// SPDX-FileCopyrightText: 2026 Dais & Apex
// SPDX-License-Identifier: AGPL-3.0-only

// Package server is demiplane's HTTP layer: POST /publish to store an artifact
// and GET /{slug} to serve it back. It is deliberately thin — slug resolution,
// streaming, and content-type live in the store package.
package server

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"log"
	"mime"
	"mime/multipart"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/daisandapex/demiplane/internal/module"
	"github.com/daisandapex/demiplane/internal/render"
	"github.com/daisandapex/demiplane/internal/store"
)

// Config holds the optional server settings beyond the store.
type Config struct {
	BaseURL   string // explicit advertised base URL; empty = derive from request Host
	AuthToken string // bearer token for write/list endpoints; empty = auth disabled
	// ContentBaseURL is the advertised origin for artifact bodies (GET /{slug}),
	// distinct from the control origin that hosts /publish, /list, DELETE — the
	// origin-isolation fix that closes the stored-XSS class (ADR 0003). Empty
	// means derive it from the request host, swapping in ContentPort.
	ContentBaseURL string
	// ContentPort is the port the artifact (content) origin listens on, used to
	// derive the advertised content URL from a request that arrived on the
	// control listener. Empty = same-origin mode (content == control origin).
	ContentPort string
	Browse      bool  // serve an HTML index of non-private artifacts at GET /
	MaxUpload   int64 // max publish body bytes; 0 = unlimited (the CLI defaults it to 100 MiB)
	// RenderTheme names the built-in theme for ?render=md pages (see
	// internal/theme: "light"/"dark"); empty = the default house style.
	RenderTheme string
	// RenderCSS, when non-empty, is a complete stylesheet that REPLACES the
	// built-in theme for ?render=md pages (the --css branding override).
	RenderCSS string
	// RenderHeader renders the sticky masthead (title + theme toggle) on
	// ?render=md pages.
	RenderHeader bool
	// RenderFooter renders the "Generated by demiplane" vanity footer on
	// ?render=md pages.
	RenderFooter bool
	// RenderFooterLink is the vanity-footer link target (empty = unlinked).
	RenderFooterLink string
	// RenderMetaHeader renders a frontmatter-driven meta-header (localized date +
	// labeled fields) on ?render=md pages; off strips frontmatter without a header.
	RenderMetaHeader bool
}

// Server wires the store and configuration into HTTP handlers.
type Server struct {
	store            *store.Store
	baseURL          string
	contentBaseURL   string
	contentPort      string
	authToken        string
	browse           bool
	maxUpload        int64
	renderTheme      string
	renderCSS        string
	renderHeader     bool
	renderFooter     bool
	renderFooterLink string
	renderMetaHeader bool
	tokenMAC         []byte                      // random key for constant-time, length-hiding token comparison
	routes           []module.RouteModule        // compiled-in route modules, mounted on the control plane
	contentRoutes    []module.ContentRouteModule // route modules that also mount on the content origin
}

// New returns a Server.
func New(st *store.Store, cfg Config) *Server {
	key := make([]byte, 32)
	// crypto/rand failure here is effectively impossible; on the off chance it
	// does, a zero key still yields a constant-time compare (just not keyed).
	_, _ = rand.Read(key)
	return &Server{
		store:            st,
		baseURL:          strings.TrimRight(cfg.BaseURL, "/"),
		contentBaseURL:   strings.TrimRight(cfg.ContentBaseURL, "/"),
		contentPort:      cfg.ContentPort,
		authToken:        cfg.AuthToken,
		browse:           cfg.Browse,
		maxUpload:        cfg.MaxUpload,
		renderTheme:      cfg.RenderTheme,
		renderCSS:        cfg.RenderCSS,
		renderHeader:     cfg.RenderHeader,
		renderFooter:     cfg.RenderFooter,
		renderFooterLink: cfg.RenderFooterLink,
		renderMetaHeader: cfg.RenderMetaHeader,
		tokenMAC:         key,
		routes:           module.RouteModules(),
		contentRoutes:    module.ContentRouteModules(),
	}
}

// mountContentRouteModules mounts every compiled-in module's content-origin
// routes and reserves the slugs they own, before the artifact catch-all. Shared
// by ContentHandler and the combined same-origin Handler so a module's
// same-origin submit path exists wherever artifact bodies are served.
func (s *Server) mountContentRouteModules(mux *http.ServeMux) {
	for _, rm := range s.contentRoutes {
		store.AddReservedSlugs(rm.ContentReserved()...)
		rm.ContentRoutes(mux, s)
	}
}

// --- module.Host implementation ---
// *Server is the Host handed to modules: the entire surface a module may touch.

// Store returns the shared artifact content store.
func (s *Server) Store() *store.Store { return s.store }

// RequireAuth exposes core's bearer-token publish-auth wrapper to modules.
func (s *Server) RequireAuth(next http.HandlerFunc) http.HandlerFunc {
	return s.requireAuth(next)
}

// RequestBase returns the advertised base URL for the request (no trailing
// slash). Exported for modules; requestBase is the internal implementation.
func (s *Server) RequestBase(r *http.Request) string { return s.requestBase(r) }

// BaseURL returns the statically configured --base-url ("" if unset).
func (s *Server) BaseURL() string { return s.baseURL }

// ModuleDataDir returns (creating if needed) a storage directory private to the
// named module, under <store-root>/modules/<name>. 0700 so password/private
// material a module persists is not world-readable, matching the blob dir.
func (s *Server) ModuleDataDir(name string) (string, error) {
	dir := filepath.Join(s.store.Root(), "modules", name)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create module data dir for %q: %w", name, err)
	}
	return dir, nil
}

// ControlHandler returns the control-plane handler: /publish, /list, DELETE,
// and the human/agent surfaces — everything EXCEPT artifact bodies. It is served
// on the control origin (the --bind listener). State-changing requests are
// screened by the cross-origin write guard so hosted JS on the content origin
// cannot drive writes (ADR 0003). Mutating + listing endpoints are behind bearer
// auth (the publish-auth layer).
func (s *Server) ControlHandler() http.Handler {
	mux := http.NewServeMux()
	s.registerControlRoutes(mux)
	return withSecurityHeaders(s.guardCrossOriginWrites(mux))
}

// ContentHandler returns the artifact-serving handler: GET /{slug} only. It is
// served on the separate content origin (the --content-bind listener) so hosted
// JS runs cross-origin to the control plane and the same-origin policy blocks it
// from reading /list or any control response (ADR 0003). View auth
// (password/private/capability) is enforced inside handleGet.
func (s *Server) ContentHandler() http.Handler {
	mux := http.NewServeMux()
	// Content-origin feature routes (SSE live-reload, multi-file sites) mount
	// before the artifact catch-all; their dynamic path shapes are more specific
	// than GET /{slug}, so ServeMux prefers them.
	s.mountCoreContentRoutes(mux)
	// Content-origin module routes (e.g. the reply module's same-origin
	// POST /{slug} answer submit) mount alongside. POST /{slug} coexists with the
	// GET /{slug} catch-all (method-distinct) and never shadows it.
	s.mountContentRouteModules(mux)
	mux.HandleFunc("GET /{slug}", s.handleGet)
	// The bare content root has no landing on this plane (the landing lives on the
	// control origin); serve the themed 404 rather than ServeMux's plaintext one.
	mux.HandleFunc("GET /{$}", s.serveContentNotFound)
	return withSecurityHeaders(mux)
}

// Handler returns a single combined handler that serves BOTH the control plane
// and artifact bodies on one origin. This is the legacy, same-origin topology —
// used only by --unsafe-same-origin (and tests) — and deliberately carries the
// stored-XSS footgun the split topology closes. Go's ServeMux prefers the more
// specific pattern, so GET /list wins over GET /{slug}; "list" and "publish" are
// reserved slug names so they can never shadow a real artifact.
func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	s.registerControlRoutes(mux)
	// Content-origin feature routes collapse onto the same mux in legacy
	// same-origin mode. They stay more specific than GET /{slug}.
	s.mountCoreContentRoutes(mux)
	s.mountContentRouteModules(mux)
	mux.HandleFunc("GET /{slug}", s.handleGet)
	return withSecurityHeaders(mux)
}

// registerControlRoutes mounts every route except the artifact catch-all
// GET /{slug}, shared by ControlHandler and the combined Handler.
func (s *Server) registerControlRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /publish", s.requireAuth(s.handlePublish))
	mux.HandleFunc("GET /list", s.requireAuth(s.handleList))
	mux.HandleFunc("DELETE /{slug}", s.requireAuth(s.handleDelete))
	// Human + agent surfaces. These literal paths win over GET /{slug} (more
	// specific), and "docs"/"help"/"llms.txt" are reserved slug names so an
	// artifact can never shadow them.
	mux.HandleFunc("GET /{$}", s.handleLanding)
	mux.HandleFunc("GET /docs", s.handleDocsIndex)
	mux.HandleFunc("GET /docs/{page}", s.handleDocsPage)
	mux.HandleFunc("GET /llms.txt", s.handleLLMs)
	// /help is the human getting-started page; the agent-native self-describing
	// JSON moved to /help.json (byte-identical to the former /help). Both are
	// reserved slugs so no artifact can shadow either route.
	mux.HandleFunc("GET /help", s.handleHelpPage)
	mux.HandleFunc("GET /help.json", s.handleHelp)

	// First-party (core, un-tagged) feature routes — /connect, /gallery, etc.
	// mount through the coreControlRoutes seam (internal/server/routes.go) so a
	// feature owns one file and never edits this function.
	s.mountCoreControlRoutes(mux)

	// Compiled-in route modules mount before the catch-all GET /{slug}. Their
	// reserved top-level segments are registered so an artifact slug can never
	// shadow a module route — the same invariant core holds for its own paths.
	for _, rm := range s.routes {
		store.AddReservedSlugs(rm.Reserved()...)
		rm.Routes(mux, s)
	}
}

// guardCrossOriginWrites rejects browser-driven state-changing requests that
// originate from another origin (ADR 0003, P2). The same-origin policy blocks
// hosted JS from READING control responses, but a "simple" cross-origin POST
// still executes server-side fire-and-forget — so a content-origin artifact's
// JS could POST /publish a worm without this guard. Reads are unaffected (SOP
// already shields their responses) and non-browser clients (curl, the SSH
// ingest path, agents — no Sec-Fetch/Origin headers) pass untouched.
func (s *Server) guardCrossOriginWrites(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if isCrossOriginWrite(r) {
			http.Error(w, "cross-origin write rejected", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// isCrossOriginWrite reports whether a state-changing request came from a
// different origin, per the browser's own fetch-metadata. Sec-Fetch-Site is
// authoritative when present (every modern browser sends it): only same-origin
// and none (a top-level/user-initiated load) are allowed; same-site (e.g. a
// different port — our content origin) and cross-site are rejected. When
// Sec-Fetch-Site is absent, fall back to comparing the Origin header to the
// listener's own host. No header at all ⇒ a non-browser client ⇒ allowed.
func isCrossOriginWrite(r *http.Request) bool {
	switch r.Method {
	case http.MethodGet, http.MethodHead, http.MethodOptions:
		return false // reads/preflights don't change state
	}
	if site := r.Header.Get("Sec-Fetch-Site"); site != "" {
		switch site {
		case "same-origin", "none":
			return false
		default: // same-site, cross-site
			return true
		}
	}
	if origin := r.Header.Get("Origin"); origin != "" {
		u, err := url.Parse(origin)
		if err != nil || u.Host == "" {
			return true // unparseable Origin on a write ⇒ refuse
		}
		return !strings.EqualFold(u.Host, r.Host)
	}
	return false // no browser signals ⇒ non-browser client (curl/SSH/agent)
}

// frameAncestorsSelf is the framing policy on every response: only same-origin
// pages may embed one (clickjacking defense, Shannon finding demiplane-t0j).
// SAMEORIGIN — not DENY — because demiplane itself frames legitimately: the
// ?live preview wrapper iframes the artifact's own URL same-origin (live.go).
// Note frame-ancestors does NOT fall back to default-src, so any handler that
// sets its own Content-Security-Policy must include this directive explicitly
// (handleGet's scriptable-type CSP, site.go, live.go all do).
const frameAncestorsSelf = "frame-ancestors 'self'"

// hstsValue is the HSTS policy emitted on TLS-terminated responses (demiplane-5ce).
// Two years, but deliberately WITHOUT includeSubDomains and WITHOUT preload: a
// public demiplane instance lives on one subdomain and must not commit sibling
// subdomains (or the apex) of its parent zone to HTTPS-only. Sent only when the
// request arrived over TLS (r.TLS != nil, i.e. the native TLS module is active),
// never on plain HTTP where advertising HSTS would be meaningless or harmful.
const hstsValue = "max-age=63072000"

// referrerPolicy keeps a capability slug (?private=true) out of the Referer
// header on cross-origin navigations away from a hosted page (demiplane-hgp).
// strict-origin-when-cross-origin still sends the full URL same-origin (so an
// artifact's own relative links keep working) but strips the path — and thus any
// capability secret — the moment the destination is a different origin. The ?live
// wrapper sets a stronger no-referrer for its preview frame (live.go), which
// overrides this baseline.
const referrerPolicy = "strict-origin-when-cross-origin"

// withSecurityHeaders sets baseline hardening headers on every response.
// nosniff stops a text/plain (or otherwise mistyped) artifact from being
// content-sniffed into text/html and executed — the MIME-confusion half of the
// stored-XSS surface. Explicitly-typed HTML pages still render (that is an
// intended demiplane feature); see handleGet for the SVG/XML no-script CSP.
// X-Frame-Options + frame-ancestors stop external sites from framing either
// plane (clickjacking); same-origin framing (the ?live wrapper) still works.
// Referrer-Policy protects capability URLs from Referer leakage; HSTS is emitted
// only over TLS (see the constants above).
func withSecurityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "SAMEORIGIN")
		w.Header().Set("Content-Security-Policy", frameAncestorsSelf)
		w.Header().Set("Referrer-Policy", referrerPolicy)
		if r.TLS != nil {
			w.Header().Set("Strict-Transport-Security", hstsValue)
		}
		next.ServeHTTP(w, r)
	})
}

// PasswordHeader is where a per-artifact view password is supplied on publish.
// It is deliberately NOT a query parameter: query strings leak into access logs,
// proxy logs, browser history, and Referer headers.
const PasswordHeader = "X-Demiplane-Password"

// handlePublish stores the request body (raw or multipart) and returns the URL.
// Query params: ?slug= (named), ?private=, ?ttl= (e.g. 30m, 2h, 7d). The view
// password is supplied via the X-Demiplane-Password header, never the URL.
func (s *Server) handlePublish(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()

	// Multi-file / directory publish hook (feature T2.2): POST /publish?site=<name>
	// ingests a tar/zip/multipart archive as a path-structured site. site.go owns
	// the whole path; nil = feature not wired into this build.
	if q.Has("site") {
		if publishSite != nil {
			publishSite(s, w, r)
		} else {
			http.Error(w, "multi-file site publish is not enabled in this build", http.StatusNotImplemented)
		}
		return
	}

	ttl, err := store.ParseTTL(q.Get("ttl"))
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	private := queryFlag(q, "private")
	named := q.Get("slug")

	// A named slug is guessable, so it cannot also be "private" — privacy here
	// is the unguessable capability URL. Allowing the combination would silently
	// produce a guessable "private" artifact (a false sense of security).
	if private && named != "" {
		http.Error(w, "private artifacts cannot use a named slug — omit ?slug= to get a capability URL", http.StatusBadRequest)
		return
	}

	// The password must not travel in the URL (logged surface). Reject it loudly
	// rather than silently accepting the leak-prone form.
	if q.Has("password") {
		http.Error(w, "supply the view password via the "+PasswordHeader+" header, not the URL query", http.StatusBadRequest)
		return
	}

	// Upload cap (0 = unlimited; the CLI defaults it to 100 MiB). When set, an
	// oversized body surfaces as *http.MaxBytesError below.
	if s.maxUpload > 0 {
		r.Body = http.MaxBytesReader(w, r.Body, s.maxUpload)
	}

	body, filename, err := openUpload(r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	defer body.Close()

	// An inline reply box (?reply=question) only makes sense baked into a
	// server-rendered page that answers at a stable, publicly-addressable URL: the
	// box posts to /answer/<slug> on the content plane, and the submit handler
	// answers only for public (non-private) slugs. Require ?render=md and a named
	// ?slug=, and reject ?private — the combinations that would otherwise produce a
	// box that can never record an answer.
	replyBox := replyRequested(q)
	if replyBox {
		if !renderRequested(q) {
			http.Error(w, "?reply requires ?render=md — the reply box is baked into the rendered page", http.StatusBadRequest)
			return
		}
		if private {
			http.Error(w, "?reply cannot be combined with ?private — a private capability page cannot collect replies", http.StatusBadRequest)
			return
		}
		if named == "" {
			http.Error(w, "?reply requires a named ?slug= — the reply box posts to that stable URL", http.StatusBadRequest)
			return
		}
	}

	// Forward flow: ?next=<slug> names the lesson that follows this page. After
	// a recorded answer, the confirmation carries the student there once it is
	// published (it need not exist yet — the whole point is that it appears
	// later). Only meaningful with a reply box; invalid combinations fail loudly.
	next := q.Get("next")
	if next != "" {
		if !replyBox {
			http.Error(w, "?next requires ?reply — it names the page that follows this one's answer", http.StatusBadRequest)
			return
		}
		if err := store.ValidateNamedSlug(next); err != nil {
			http.Error(w, "?next: "+err.Error(), http.StatusBadRequest)
			return
		}
		if next == named {
			http.Error(w, "?next must name a different slug than ?slug — a page cannot follow itself", http.StatusBadRequest)
			return
		}
	}

	// Optional markdown→HTML render. This path buffers the (small) document
	// rather than streaming, bounded by maxRenderBytes.
	var src io.Reader = body
	if renderRequested(q) {
		data, rerr := io.ReadAll(io.LimitReader(body, maxRenderBytes+1))
		if rerr != nil {
			// An over-limit body (when --max-upload is set) surfaces here too —
			// return 413, not a generic 500.
			var maxErr *http.MaxBytesError
			if errors.As(rerr, &maxErr) {
				http.Error(w, "upload exceeds the configured size limit", http.StatusRequestEntityTooLarge)
				return
			}
			log.Printf("render read failed: %v", rerr)
			http.Error(w, "internal error", http.StatusInternalServerError)
			return
		}
		if len(data) > maxRenderBytes {
			http.Error(w, "markdown document too large to render", http.StatusRequestEntityTooLarge)
			return
		}
		// Colophon metadata (demiplane-rwj): the renderer self-measures the
		// document's own byte length for "size" (that length IS the stored artifact
		// size), so we only supply the publish time, the same-family siblings for
		// series prev/next, and the base URLs. Siblings are the already-published,
		// non-private artifacts sharing this slug's prefix family (the gallery's
		// grouping); a named-slug requirement keeps auto-generated capability slugs
		// out of accidental families. A List error is non-fatal — the colophon just
		// shows the meta row with no series nav.
		var siblings []string
		if named != "" {
			if arts, lerr := s.store.List(store.DefaultOwner); lerr == nil {
				grp := slugGroup(named)
				for _, a := range arts {
					if a.Slug != named && slugGroup(a.Slug) == grp {
						siblings = append(siblings, a.Slug)
					}
				}
			}
		}
		src = bytes.NewReader(render.Markdown(data, render.Options{
			Theme:       s.renderTheme,
			CSS:         s.renderCSS,
			Title:       named, // slug fallback; the body's first H1 wins when present
			Header:      s.renderHeader,
			Footer:      s.renderFooter,
			FooterLink:  s.renderFooterLink,
			MetaHeader:  s.renderMetaHeader,
			ReplySlug:   replySlugFor(replyBox, named),
			ReplyNext:   next, // validated above; "" unless a reply box is baked
			Colophon:    true,
			Slug:        named,
			Published:   time.Now(),
			Siblings:    siblings,
			ContentBase: s.contentBase(r),
			IndexURL:    s.requestBase(r) + "/gallery",
		}))
		filename = renderedName(filename)
	}

	opts := store.PutOptions{
		Slug:     named,
		Filename: filename,
		Private:  private,
		Password: r.Header.Get(PasswordHeader),
		TTL:      ttl,
	}
	art, err := s.store.Put(opts, src)
	if err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			http.Error(w, "upload exceeds the configured size limit", http.StatusRequestEntityTooLarge)
			return
		}
		if isClientError(err) {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		log.Printf("publish failed: %v", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	url := s.artifactURL(r, art.Slug)
	if wantsJSON(r) {
		writeJSON(w, http.StatusCreated, map[string]any{
			"url":          url,
			"slug":         art.Slug,
			"content_type": art.ContentType,
			"size":         art.Size,
			"private":      art.Private,
			"password":     art.HasPassword(),
			"expires_at":   rfc3339OrEmpty(art.ExpiresAt),
		})
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusCreated)
	fmt.Fprintln(w, url)
}

// handleGet serves an artifact's bytes with the stored content-type, inline or
// as an attachment per the store's policy. Password-protected artifacts require
// HTTP Basic credentials (the password; username is ignored).
func (s *Server) handleGet(w http.ResponseWriter, r *http.Request) {
	// Live-preview hook (feature T2.1): a ?live view is served by live.go wrapped
	// in a first-party reload snippet. It NEVER mutates stored bytes, so the
	// default (non-live) path below stays byte-identical. Nil when unwired.
	if liveView != nil && liveView(s, w, r) {
		return
	}

	slug := r.PathValue("slug")

	art, f, err := s.store.Get(slug)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			// Unknown or past-TTL slug: a reader followed a stale/expired link.
			// Serve the themed content-plane 404, not Go's plaintext one.
			s.serveContentNotFound(w, r)
			return
		}
		log.Printf("get %s failed: %v", redactSlug(slug), err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	defer f.Close()

	if art.HasPassword() && !passwordOK(r, art.PasswordHash) {
		w.Header().Set("WWW-Authenticate", `Basic realm="demiplane", charset="UTF-8"`)
		http.Error(w, "password required", http.StatusUnauthorized)
		return
	}

	w.Header().Set("Content-Type", art.ContentType)
	if store.IsScriptableNonHTML(art.ContentType) {
		// SVG/XML/XHTML render as active documents and would execute embedded
		// <script> at our origin. demiplane intentionally hosts executable HTML
		// pages, but these types are expected to be inert content — block script
		// execution so a published image/document can't become stored XSS. This
		// Set replaces the baseline frame-ancestors CSP, so re-state it here.
		w.Header().Set("Content-Security-Policy", "script-src 'none'; "+frameAncestorsSelf)
	}
	if store.IsInline(art.ContentType) {
		w.Header().Set("Content-Disposition", "inline")
	} else {
		w.Header().Set("Content-Disposition",
			fmt.Sprintf("attachment; filename=%q", sanitizeFilename(art.Filename)))
	}
	// Artifacts are mutable (re-publishing a slug overwrites in place), so a
	// browser must revalidate rather than serve a heuristically-cached stale
	// copy — otherwise ?live reloads, and any re-view of an updated artifact,
	// show old bytes. no-cache pairs with the Last-Modified below: a conditional
	// GET returns 304 when unchanged and fresh bytes when re-published.
	w.Header().Set("Cache-Control", "no-cache")
	// ServeContent handles Range requests, conditional GETs, and keeps the
	// content-type we set above. CreatedAt is the publish time we recorded,
	// which advances on every re-publish and drives the Last-Modified header.
	http.ServeContent(w, r, art.Filename, art.CreatedAt, f)
}

// openUpload returns a reader over the uploaded bytes plus a filename hint. It
// transparently handles multipart/form-data (first file part) and raw bodies.
// The returned ReadCloser must be closed by the caller.
func openUpload(r *http.Request) (io.ReadCloser, string, error) {
	ct := r.Header.Get("Content-Type")
	mediaType, _, _ := mime.ParseMediaType(ct)
	if mediaType == "multipart/form-data" {
		return openMultipart(r)
	}
	// Raw body. An explicit ?filename= lets callers supply an extension hint.
	return r.Body, r.URL.Query().Get("filename"), nil
}

// openMultipart streams the first file part of a multipart request without
// buffering it. It returns a reader tied to the part plus its filename.
func openMultipart(r *http.Request) (io.ReadCloser, string, error) {
	mr, err := r.MultipartReader()
	if err != nil {
		return nil, "", fmt.Errorf("parse multipart: %w", err)
	}
	for {
		part, err := mr.NextPart()
		if err == io.EOF {
			return nil, "", errors.New("multipart body has no file part")
		}
		if err != nil {
			return nil, "", fmt.Errorf("read multipart: %w", err)
		}
		if part.FileName() == "" {
			part.Close()
			continue
		}
		return &partReadCloser{part: part}, part.FileName(), nil
	}
}

// partReadCloser adapts a multipart.Part to io.ReadCloser semantics that close
// the part on completion.
type partReadCloser struct{ part *multipart.Part }

func (p *partReadCloser) Read(b []byte) (int, error) { return p.part.Read(b) }
func (p *partReadCloser) Close() error               { return p.part.Close() }

// handleDelete removes an artifact (blob + metadata). Returns 204 on success,
// 404 if the slug is unknown.
func (s *Server) handleDelete(w http.ResponseWriter, r *http.Request) {
	slug := r.PathValue("slug")
	if err := s.store.Delete(slug); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			http.NotFound(w, r)
			return
		}
		log.Printf("delete %s failed: %v", redactSlug(slug), err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// listItem is one entry in the GET /list response. The password hash is never
// included — only whether a password gate exists.
type listItem struct {
	Slug        string `json:"slug"`
	URL         string `json:"url"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
	CreatedAt   string `json:"created_at"`
	Owner       string `json:"owner"`
	Private     bool   `json:"private"`
	Password    bool   `json:"password"`
	ExpiresAt   string `json:"expires_at,omitempty"`
}

// handleList returns the caller's artifacts as JSON, newest first. In v1 the
// caller is the single local owner.
func (s *Server) handleList(w http.ResponseWriter, r *http.Request) {
	arts, err := s.store.List(store.DefaultOwner)
	if err != nil {
		log.Printf("list failed: %v", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	base := s.contentBase(r)
	items := make([]listItem, 0, len(arts))
	for _, a := range arts {
		items = append(items, listItem{
			Slug:        a.Slug,
			URL:         base + "/" + a.Slug,
			Filename:    a.Filename,
			ContentType: a.ContentType,
			Size:        a.Size,
			CreatedAt:   a.CreatedAt.Format(time.RFC3339),
			Owner:       a.Owner,
			Private:     a.Private,
			Password:    a.HasPassword(),
			ExpiresAt:   rfc3339OrEmpty(a.ExpiresAt),
		})
	}
	writeJSON(w, http.StatusOK, map[string]any{"artifacts": items, "count": len(items)})
}

// maxRenderBytes bounds how much markdown the render path will buffer.
const maxRenderBytes = 8 << 20 // 8 MiB

// renderRequested reports whether the publish asked for markdown rendering via
// ?render=md|markdown.
func renderRequested(q url.Values) bool {
	switch strings.ToLower(q.Get("render")) {
	case "md", "markdown":
		return true
	}
	return false
}

// replyRequested reports whether the publish asked for an inline reply box via
// ?reply=question (the Q&A/teaching mode) or a plain truthy ?reply. The box is a
// server-rendered, JS-free form that posts same-origin to the page's own URL.
func replyRequested(q url.Values) bool {
	if !q.Has("reply") {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(q.Get("reply"))) {
	case "0", "false", "no", "off":
		return false
	default: // "question", "comment", "1", "true", "on", bare ?reply
		return true
	}
}

// replySlugFor returns the slug the rendered page's reply box should target, or
// "" to omit the box. handlePublish has already validated that a named slug is
// present whenever the box was requested.
func replySlugFor(enabled bool, named string) string {
	if enabled {
		return named
	}
	return ""
}

// renderedName returns a filename whose extension is .html (so the stored
// artifact is served as HTML), derived from the upload's name when possible.
func renderedName(filename string) string {
	switch {
	case filename == "":
		return "page.html"
	case strings.HasSuffix(filename, ".md"):
		return strings.TrimSuffix(filename, ".md") + ".html"
	case strings.HasSuffix(filename, ".markdown"):
		return strings.TrimSuffix(filename, ".markdown") + ".html"
	case strings.HasSuffix(filename, ".html"):
		return filename
	default:
		return filename + ".html"
	}
}

// handleLanding renders the welcoming landing at GET /. It orients a newcomer
// regardless of state: the privacy ethos, a copy-pasteable publish one-liner,
// the endpoint vocabulary, and pointers to /docs, /llms.txt, and /help. When
// --browse is enabled it also lists the (non-private) artifacts; otherwise it
// only shows the count, so slugs are never leaked by default.
func (s *Server) handleLanding(w http.ResponseWriter, r *http.Request) {
	base := s.requestBase(r)
	count, err := s.store.Count(store.DefaultOwner)
	if err != nil {
		log.Printf("landing count failed: %v", err)
		count = -1
	}

	var b strings.Builder
	b.WriteString(`<span class="kicker">Self-hosted publishing</span>`)
	b.WriteString(`<h1>demiplane</h1>`)
	b.WriteString(`<p class="tagline">Your private publishing plane.</p>`)
	b.WriteString(`<span class="ethos">Sealed by default, shared by choice.</span>`)
	b.WriteString(`<p>POST a file, get a URL, fetch it back, over your own network. ` +
		`The honest inverse of public paste/host services.</p>`)

	b.WriteString(`<h2>Publish your first page</h2>`)
	b.WriteString(codeBlock("Request", publishHint(base)))
	b.WriteString(`<p>It returns a friendly URL like <code>` + html.EscapeString(base) +
		`/shadow-specter</code>. Add <code>?slug=reports</code> for a stable name that ` +
		`overwrites in place, <code>?private=true</code> for an unguessable capability URL, or ` +
		`<code>?ttl=24h</code> to auto-expire.</p>`)

	b.WriteString(`<h2>Endpoints</h2>`)
	b.WriteString(endpointCard("POST", "/publish", "Store a file (raw or multipart); returns the URL."))
	b.WriteString(endpointCard("GET", "/{slug}", "Fetch an artifact as-is (password-gated ones prompt)."))
	b.WriteString(endpointCard("GET", "/list", "JSON list of your artifacts."))
	b.WriteString(endpointCard("DELETE", "/{slug}", "Remove an artifact."))

	// No "Learn more" tile grid: every primary surface (Docs, API, Connect,
	// Gallery, Help, llms.txt) is now one click away in the top nav, so a tile
	// row would only duplicate it (demiplane-6va).

	// State line + optional artifact listing.
	authState := "open (no token configured)"
	if s.authToken != "" {
		authState = "bearer token required for write/list"
	}
	if count >= 0 {
		fmt.Fprintf(&b, `<p class="kicker">This instance</p><p>%s · auth: %s</p>`,
			plural(count, "artifact"), html.EscapeString(authState))
	}
	if s.browse {
		b.WriteString(s.artifactTable(r))
	}

	writeHTML(w, s.pageHTML("demiplane", topNav("/"), b.String()))
}

// landingTableCap bounds the landing's "Published" preview: the newest few, with
// a link to /gallery for the rest. The full wall lives at /gallery; the landing
// only teases it (the report's "landing is two pages pretending to be one" fix).
const landingTableCap = 8

// landingRow is one row of the landing "Published" table after series collapse.
// A single-member family renders as its own slug; a family of two or more folds
// into one reference (label = the shared prefix, count = the size, slug = the
// newest member the row links to).
type landingRow struct {
	label   string    // display text: full slug (singleton) or prefix (series)
	slug    string    // link target: the row's own slug, or the newest member's
	count   int       // family size (1 for a singleton)
	created time.Time // newest member's publish time
	locked  bool      // lock glyph (singletons only; a series is mixed)
}

// collapseSeries folds a newest-first artifact slice into landing rows, grouping
// by slug prefix (slugGroup: text before the first hyphen). A family of two or
// more collapses to a single reference linking to its newest member; a lone
// artifact stays a plain row (no forced "(1)"). Row order follows first-sighting,
// which — because the input is newest-first — orders families by their newest
// member. This is the landing analogue of the gallery's client-side prefix
// grouping (demiplane-0pw).
func collapseSeries(pub []store.Artifact) []landingRow {
	type acc struct {
		idx     int // position in rows, to update in place
		members int
	}
	seen := make(map[string]*acc)
	var rows []landingRow
	for _, a := range pub {
		key := slugGroup(a.Slug)
		if g, ok := seen[key]; ok {
			// A second (or later) member promotes the row to a series: relabel to
			// the shared prefix, bump the count. The link/date stay on the newest
			// member (the first one seen), and a mixed family drops the lock glyph.
			rows[g.idx].label = key
			rows[g.idx].count = g.members + 1
			rows[g.idx].locked = false
			g.members++
			continue
		}
		rows = append(rows, landingRow{
			label:   a.Slug,
			slug:    a.Slug,
			count:   1,
			created: a.CreatedAt,
			locked:  a.HasPassword(),
		})
		seen[key] = &acc{idx: len(rows) - 1, members: 1}
	}
	return rows
}

// artifactTable renders the non-private artifact listing for the --browse case.
// Private artifacts are excluded (their capability slug is the secret). Links
// point at the CONTENT origin via contentBase (ADR 0003): the control-plane base
// has no GET /{slug}, so linking there returned 405. store.List is newest-first;
// a slug-series collapses to one row (collapseSeries) and the preview is capped
// at landingTableCap with an "all N" link to /gallery. The table shows the slug
// and the published date only — type/size clutter lives in the API, not here
// (demiplane-0pw).
func (s *Server) artifactTable(r *http.Request) string {
	arts, err := s.store.List(store.DefaultOwner)
	if err != nil {
		log.Printf("browse list failed: %v", err)
		return ""
	}
	base := s.contentBase(r)

	// Collect the public artifacts (newest-first order preserved from store.List).
	var pub []store.Artifact
	for _, a := range arts {
		if a.Private {
			continue
		}
		pub = append(pub, a)
	}

	var b strings.Builder
	b.WriteString(`<h2>Published</h2>`)
	if len(pub) == 0 {
		b.WriteString(`<p><em>No public artifacts yet. Publish one above.</em></p>`)
		return b.String()
	}

	rows := collapseSeries(pub)

	b.WriteString(`<table><thead>`)
	b.WriteString(`<tr><th>artifact</th><th>published</th></tr>`)
	b.WriteString(`</thead><tbody>`)
	shown := rows
	if len(shown) > landingTableCap {
		shown = shown[:landingTableCap]
	}
	for _, row := range shown {
		label := html.EscapeString(row.label)
		if row.count > 1 {
			// A series reads as "dispatch (8) →", linking to the newest member.
			label = fmt.Sprintf(`%s <span class="scount">(%d)</span> →`, label, row.count)
		} else if row.locked {
			label += " 🔒"
		}
		fmt.Fprintf(&b,
			`<tr><td><a href="%s/%s">%s</a></td><td>%s</td></tr>`,
			html.EscapeString(base), html.EscapeString(row.slug), label,
			row.created.Format("2006-01-02 15:04"))
	}
	b.WriteString(`</tbody></table>`)
	if len(rows) > landingTableCap {
		fmt.Fprintf(&b, `<p><a href="/gallery">All %s → /gallery</a></p>`, plural(len(pub), "artifact"))
	} else {
		b.WriteString(`<p><a href="/gallery">Browse the gallery →</a></p>`)
	}
	return b.String()
}

// plural formats a count with its noun, adding an "s" for anything but 1, so
// human copy reads "1 artifact" / "5 artifacts" instead of "artifact(s)".
func plural(n int, noun string) string {
	if n == 1 {
		return "1 " + noun
	}
	return strconv.Itoa(n) + " " + noun + "s"
}

// redactSlug returns a short, non-reversible tag for a slug so error logs never
// leak the slug itself — for a private artifact the slug IS the capability
// secret, and logs are a common exposure surface.
func redactSlug(slug string) string {
	sum := sha256.Sum256([]byte(slug))
	return "slug#" + hex.EncodeToString(sum[:])[:12]
}

// shortType trims charset/boundary params from a content type for display.
func shortType(ct string) string {
	if i := strings.IndexByte(ct, ';'); i >= 0 {
		return strings.TrimSpace(ct[:i])
	}
	return ct
}

// requestBase returns the advertised base URL (no trailing slash). With
// --base-url set it is authoritative; otherwise scheme+host are derived from
// the request. X-Forwarded-* are deliberately NOT consulted (host-header /
// proto spoofing defense), and the reflected host is sanitized: it flows into
// response bodies (llms.txt, publish responses, minted URLs), so a crafted
// Host header must not be able to inject arbitrary content there.
func (s *Server) requestBase(r *http.Request) string {
	if s.baseURL != "" {
		return s.baseURL
	}
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	return scheme + "://" + sanitizeHost(r.Host)
}

// sanitizeHost strips every character outside the URI host grammar (RFC 3986
// reg-name letters/digits/. /- /_ plus the :port separator and IPv6 brackets).
// Legitimate Host headers pass through untouched; a crafted one cannot smuggle
// spaces, quotes, angle brackets, or control characters into the plain-text and
// HTML surfaces that reflect the request host (Shannon finding demiplane-6y9).
func sanitizeHost(host string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		case r == '.', r == '-', r == ':', r == '[', r == ']', r == '_':
			return r
		}
		return -1
	}, host)
}

// contentBase returns the advertised origin for artifact bodies (GET /{slug}).
// Artifacts live on a separate origin from the control plane (ADR 0003), so a
// URL minted while handling a control-listener request (/publish, /list) must
// point at the content origin, not the request's own host. Resolution order:
//  1. an explicit --content-base-url (proxy/TLS deployments);
//  2. derive from the request host, swapping in the content port (the zero-config
//     two-port default — handles loopback and wildcard binds alike);
//  3. same-origin mode (no content port): the request origin itself.
func (s *Server) contentBase(r *http.Request) string {
	if s.contentBaseURL != "" {
		return s.contentBaseURL
	}
	if s.contentPort == "" {
		return s.requestBase(r)
	}
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	host := sanitizeHost(r.Host)
	if h, _, err := net.SplitHostPort(host); err == nil {
		host = h
	}
	return scheme + "://" + net.JoinHostPort(host, s.contentPort)
}

// artifactURL builds the full URL for a slug on the content origin.
func (s *Server) artifactURL(r *http.Request, slug string) string {
	return s.contentBase(r) + "/" + slug
}

func wantsJSON(r *http.Request) bool {
	return strings.Contains(r.Header.Get("Accept"), "application/json")
}

// queryFlag reports whether a boolean query parameter is set true. A bare
// "?private" (present, empty value) counts as true; "?private=false" (and 0/no/
// off) counts as false; an absent key is false.
func queryFlag(q url.Values, key string) bool {
	if !q.Has(key) {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(q.Get(key))) {
	case "0", "false", "no", "off":
		return false
	default:
		return true
	}
}

// passwordOK reports whether the request carries HTTP Basic credentials whose
// password matches the artifact's hash. The username is ignored.
func passwordOK(r *http.Request, hash string) bool {
	_, pass, ok := r.BasicAuth()
	if !ok {
		return false
	}
	return store.PasswordMatches(hash, pass)
}

// rfc3339OrEmpty formats t as RFC3339, or "" for the zero time.
func rfc3339OrEmpty(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(time.RFC3339)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// isClientError reports whether err is a user-input problem (bad slug, invalid
// option combination) that should be a 400 rather than a 500. It matches the
// typed store.InputError, not error text — robust to message changes and to
// internal errors that happen to mention "slug".
func isClientError(err error) bool {
	var ie *store.InputError
	return errors.As(err, &ie)
}

// sanitizeFilename strips characters that would break the Content-Disposition
// header. Quotes and control characters are removed; the rest passes through.
func sanitizeFilename(name string) string {
	name = strings.Map(func(r rune) rune {
		if r < 0x20 || r == '"' || r == '\\' || r == '/' {
			return -1
		}
		return r
	}, name)
	if name == "" {
		return "download"
	}
	return name
}
