// SPDX-FileCopyrightText: 2026 Dais & Apex
// SPDX-License-Identifier: AGPL-3.0-only

// Package render provides demiplane's optional, dependency-free markdown→HTML
// rendering. It implements a deliberate *subset* of CommonMark — headings,
// fenced code, lists, blockquotes, horizontal rules, paragraphs, and inline
// code/bold/italic/links — which covers the report-style documents demiplane is
// built to host. It is NOT a complete CommonMark implementation; if richer
// rendering is ever needed, a vetted library can be swapped in behind this same
// Markdown function. All source text is HTML-escaped before inline formatting,
// so raw HTML/JS in the markdown source cannot inject into the rendered page.
package render

import (
	"html"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/daisandapex/demiplane/internal/theme"
)

// Options controls how Markdown wraps rendered content in a styled document.
// The zero value renders the default house style (theme.Default) with no
// masthead or footer (callers opt into the chrome explicitly).
type Options struct {
	// Theme selects a built-in theme by name (see internal/theme: "light" /
	// "dark"). Empty means "no explicit server theme": the page renders light
	// server-side, and the client toggle's initial state falls back to the OS
	// prefers-color-scheme. A non-empty value is the initial/default theme.
	Theme string
	// CSS, when non-empty, is a complete stylesheet that REPLACES the built-in
	// theme — the --css self-host-branding override. Trusted operator input
	// (a file path the operator chose), injected verbatim into <style>. When
	// set, the client light/dark toggle is disabled (the custom sheet owns the
	// look and need not define both token sets).
	CSS string
	// Title is the fallback document title for the masthead, used when the body
	// has no level-1 heading. Typically the artifact slug.
	Title string
	// Header renders the sticky masthead (document title + theme toggle). When
	// set, the body's first H1 is lifted into the masthead (not duplicated).
	Header bool
	// Footer renders the "Generated by demiplane" vanity footer.
	Footer bool
	// FooterLink is the footer link target; empty renders the wordmark unlinked.
	FooterLink string
	// MetaHeader controls YAML-frontmatter handling. When true, a leading
	// `---`-fenced `key: value` block is lifted out of the body and rendered as a
	// styled meta-header (a localized date/published tstamp plus one labeled line
	// per remaining field) below the masthead title. When false, any frontmatter
	// is stripped and ignored (no header). With no frontmatter, behavior is
	// unchanged either way.
	MetaHeader bool
	// ReplySlug, when non-empty, bakes a first-class inline reply box at the foot
	// of the page (the ?reply=question publish mode). It is the artifact's own
	// (named) slug: the box's JS-free <form> posts to /answer/<slug> — an
	// absolute-path action, so it lands SAME-ORIGIN on the content plane that
	// served the page (scheme inherited → correct once TLS lands). The content
	// plane's submit handler renders a server-truth confirmation, so false success
	// is structurally impossible. A single free-text answer is recorded as a
	// comment-kind reply, fitting Q&A/teaching use. It must be a URL-safe slug (it
	// always is by construction) and is attribute-escaped defensively.
	ReplySlug string
	// Colophon, when true, appends the editorial colophon at the foot of the
	// document (demiplane-rwj items 1+2): an optional series prev/next nav row and
	// a meta row (published date · size · link to the instance gallery). Enabled
	// for the ?render=md publish path; the metadata below feeds it.
	Colophon bool
	// Slug is the artifact's own slug — the series family key and the anchor the
	// prev/next order around. Distinct from Title, which the body's first H1 may
	// override; the series computation must key off the stable slug, not the title.
	Slug string
	// Published is the artifact's publish timestamp, shown (date only) in the
	// colophon meta row. It matches the stored CreatedAt (set moments later at Put).
	Published time.Time
	// Siblings lists the slugs of already-published artifacts in the same slug
	// family (shared prefix before the first hyphen), from which series prev/next is
	// computed. It excludes the current artifact, which is not yet stored at render
	// time. A family of fewer than two total members renders no nav row (a singleton
	// shows the meta row alone).
	Siblings []string
	// ContentBase is the origin the series prev/next links are minted against (the
	// content plane that serves artifact bodies, ADR 0003). Empty renders the nav
	// slugs unlinked.
	ContentBase string
	// IndexURL is the absolute link for the colophon's "all artifacts →" — the
	// instance gallery on the control plane, honoring the base-URL convention so it
	// stays instance-portable. Empty omits the link.
	IndexURL string
	// ReplyNext, when non-empty (only meaningful with ReplySlug), names the
	// FOLLOW-UP slug the student flows to after answering — the ?next= publish
	// param. It travels as a hidden form field; after a recorded answer the
	// confirmation page waits for this slug to be published and then carries the
	// student there. Validated at publish (slug-shaped, ≠ ReplySlug) and
	// re-validated at submit (a hidden field is client-tamperable).
	ReplyNext string
}

var (
	reHeading = regexp.MustCompile(`^(#{1,6})\s+(.*)$`)
	reOrdered = regexp.MustCompile(`^\d+\.\s+(.*)$`)
	reHRule   = regexp.MustCompile(`^(-{3,}|\*{3,}|_{3,})$`)
	// reTableSep matches a GFM table separator row, e.g. |---|:--:|--:| (with
	// optional alignment colons), so a preceding pipe row is treated as a header.
	reTableSep = regexp.MustCompile(`^\s*\|?\s*:?-+:?\s*(\|\s*:?-+:?\s*)*\|?\s*$`)

	// reTag matches an HTML tag, for reducing inline-rendered title HTML to the
	// plain text an element <title> needs.
	reTag = regexp.MustCompile(`<[^>]*>`)

	// Inline patterns, applied to already-escaped text.
	reCode    = regexp.MustCompile("`([^`]+)`")
	reLink    = regexp.MustCompile(`\[([^\]]+)\]\(([^)\s]+)\)`)
	reBold    = regexp.MustCompile(`\*\*([^*]+)\*\*`)
	reItalic  = regexp.MustCompile(`\*([^*]+)\*`)
	reItalicU = regexp.MustCompile(`_([^_]+)_`)
)

// Markdown renders src as a complete, styled HTML document (used for the
// ?render=md publish path). opts selects the theme/custom stylesheet and the
// optional masthead + footer chrome; the design tokens and typography are the
// same the /docs pages use, shared via internal/theme.
func Markdown(src []byte, opts Options) []byte {
	body := src

	// Frontmatter: a leading `---`-fenced key:value block. When the meta-header is
	// on we render it below the title; when off (or always, if it's there) we
	// strip it so the raw fence never leaks into the body. No frontmatter → no-op.
	var metaHTML string
	var metaNeedsScript bool
	if fields, rest, ok := parseFrontmatter(body); ok {
		body = rest
		if opts.MetaHeader {
			metaHTML, metaNeedsScript = metaHeader(fields)
		}
	}

	// The masthead shows the document title; lifting the first H1 into it avoids
	// a duplicate giant title in the body. Without a header, the H1 stays put.
	title := html.EscapeString(opts.Title)
	if opts.Header {
		if h1, rest := splitFirstH1(body); h1 != "" {
			title, body = h1, rest
		}
	}
	if title == "" {
		title = "Untitled"
	}
	// titleText is the plain-text form for the <head><title>: the masthead title
	// may carry inline markup (a lifted H1 rendered <code>/<em>/<a>), which is
	// inert in an element title, so strip tags. Entities stay escaped.
	titleText := stripTags(title)

	// Stylesheet: a --css override owns the look (toggle off); a pinned named
	// theme (catppuccin/dracula/one-dark) fixes its single palette (toggle off,
	// nothing to flip to); otherwise the masthead ships both token sets so the
	// client light/dark toggle can flip instantly.
	toggle := opts.CSS == "" && opts.Header && !theme.Pinned(opts.Theme)
	var css string
	switch {
	case opts.CSS != "":
		css = opts.CSS
	case toggle:
		css = theme.ToggleCSS()
	default:
		css = theme.CSS(opts.Theme)
	}
	if opts.Header || opts.Footer {
		css += docChromeCSS
	}
	if metaHTML != "" {
		css += metaHeadCSS
	}
	if opts.ReplySlug != "" {
		css += replyBoxCSS
	}
	if opts.Colophon {
		css += coloCSS
	}
	// The print sheet forces a page-friendly light palette and unsticks the
	// chrome regardless of the on-screen theme. Skip it only when the operator
	// supplied a full --css override (their sheet owns print too).
	if opts.CSS == "" {
		css += printCSS
	}

	var b strings.Builder
	b.WriteString(docHead(css, titleText, opts.Theme, toggle))
	if opts.Header {
		b.WriteString(masthead(title, opts.Theme, toggle))
	}
	b.WriteString("<main class=\"wrap\">\n")
	b.WriteString(metaHTML)
	bodyHTML := Body(body)
	if opts.Header {
		// The first body paragraph is the document's dek. Tag it explicitly so the
		// lead treatment targets .lead, not a positional selector that breaks the
		// moment a frontmatter meta-header is injected ahead of the body.
		bodyHTML = tagLead(bodyHTML)
	}
	b.WriteString(bodyHTML)
	if opts.ReplySlug != "" {
		b.WriteString(replyBox(opts.ReplySlug, opts.ReplyNext))
	}
	if opts.Colophon {
		b.WriteString(colophon(opts))
	}
	b.WriteString("</main>\n")
	if opts.Footer {
		b.WriteString(footerHTML(opts.FooterLink))
	}
	if opts.Header {
		b.WriteString(docChromeScript)
	}
	if metaNeedsScript {
		b.WriteString(tstampScript)
	}
	b.WriteString(docTail)
	// The colophon's size sentinel is now resolved against the finished document
	// length — the exact byte count the store will record for this artifact.
	return []byte(fillSize(b.String()))
}

// splitFirstH1 returns the inline-rendered text of the document's first level-1
// heading and src with that heading line removed, so the title can move into the
// masthead without being duplicated in the body. Headings inside fenced code are
// ignored. If there is no H1, it returns "" and the original src unchanged.
func splitFirstH1(src []byte) (titleHTML string, rest []byte) {
	lines := strings.Split(strings.ReplaceAll(string(src), "\r\n", "\n"), "\n")
	inFence := false
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		if strings.HasPrefix(t, "```") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}
		if m := reHeading.FindStringSubmatch(t); m != nil && len(m[1]) == 1 {
			kept := append(append([]string{}, lines[:i]...), lines[i+1:]...)
			return inline(m[2]), []byte(strings.Join(kept, "\n"))
		}
	}
	return "", src
}

// masthead renders the sticky title bar: a kicker (the wordmark, small-caps and
// accented), the document title set as the page's single display-serif H1, and,
// unless a custom stylesheet is in force, the light/dark toggle. The toggle
// carries both a sun and a moon SVG; CSS shows the one matching data-theme.
//
// serverTheme is the resolved initial theme ("" | light | dark); the toggle's
// aria-pressed reports "dark is active" for assistive tech. It is a server best
// guess (the client init script may resolve a different theme from localStorage /
// prefers-color-scheme); docChromeScript re-syncs aria-pressed on load and flips
// it on click, so the exposed state always matches the actual data-theme.
func masthead(titleHTML, serverTheme string, toggle bool) string {
	var b strings.Builder
	b.WriteString(`<header class="docbar"><div class="wrap"><div class="masthead">`)
	b.WriteString(`<span class="kicker">demiplane</span>`)
	b.WriteString(`<h1 class="doctitle">` + titleHTML + `</h1>`)
	b.WriteString(`</div>`)
	if toggle {
		pressed := "false"
		if serverTheme == "dark" {
			pressed = "true"
		}
		b.WriteString(`<button class="themetoggle" type="button" aria-pressed="` + pressed + `" ` +
			`aria-label="Toggle light or dark theme" title="Toggle theme">` +
			sunSVG + moonSVG + `</button>`)
	}
	b.WriteString("</div></header>\n")
	return b.String()
}

// stripTags reduces inline-rendered HTML to its text content by removing tags.
// Used to derive the element <title> from a masthead title that may carry inline
// markup; HTML entities in the text are left escaped (valid title content).
func stripTags(s string) string { return reTag.ReplaceAllString(s, "") }

// tagLead marks the first paragraph of rendered body HTML as the lead/dek by
// adding class="lead", but only when the document actually leads with a
// paragraph (not a heading, list, or table). The renderer knows the block
// structure, so this replaces the fragile positional CSS selector.
func tagLead(bodyHTML string) string {
	if strings.HasPrefix(bodyHTML, "<p>") {
		return strings.Replace(bodyHTML, "<p>", `<p class="lead">`, 1)
	}
	return bodyHTML
}

// headingText reduces a heading's raw markdown to the plain text used for its
// slug id and permalink aria-label: it runs the same inline pipeline the body
// uses (so [text](url) collapses to "text", `code` to "code", **bold** to
// "bold"), strips the resulting tags, and unescapes entities back to literal
// text. slugify then keeps only [a-z0-9-], and the aria-label re-escapes for the
// attribute, so no unescaped source can reach either sink.
func headingText(raw string) string {
	return html.UnescapeString(stripTags(inline(raw)))
}

// slugify builds a URL-safe fragment id from heading text: lowercased, runs of
// whitespace or existing hyphens collapse to a single hyphen, every other
// character (punctuation, entities, non-ASCII) is dropped, and leading/trailing
// hyphens are trimmed. The output is drawn from [a-z0-9-] only, so it is safe to
// interpolate into both an id attribute and an href fragment without escaping.
func slugify(s string) string {
	var b strings.Builder
	prevHyphen := false
	for _, r := range strings.ToLower(s) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
			prevHyphen = false
		case r == ' ' || r == '\t' || r == '-' || r == '_':
			if b.Len() > 0 && !prevHyphen {
				b.WriteByte('-')
				prevHyphen = true
			}
		}
	}
	return strings.TrimRight(b.String(), "-")
}

// uniqueSlug returns slugify(text) made unique within one document by appending
// a numeric suffix (-1, -2, …) on collision, recording every id it hands out
// (including the suffixed forms) so a later natural "foo-1" heading cannot
// duplicate a generated one. An empty slug (a heading of only punctuation or
// emoji) falls back to "section". Deterministic for a given heading sequence.
func uniqueSlug(text string, used map[string]bool) string {
	base := slugify(text)
	if base == "" {
		base = "section"
	}
	s := base
	for i := 1; used[s]; i++ {
		s = base + "-" + strconv.Itoa(i)
	}
	used[s] = true
	return s
}

// headingAnchor renders the quiet hover-'#' permalink placed at the end of every
// rendered heading. It links to the heading's own fragment and carries an
// aria-label ("Permalink to <heading>") for assistive tech. id is slug-safe by
// construction; plain is attribute-escaped. The affordance is hidden until the
// heading is hovered or the link is focused (see contentCSS .heading-anchor), and
// reserves its own space so revealing it shifts no layout.
func headingAnchor(id, plain string) string {
	return `<a class="heading-anchor" href="#` + id +
		`" aria-label="Permalink to ` + html.EscapeString(plain) + `">#</a>`
}

// sunSVG / moonSVG are crisp inline stroke icons (currentColor, no external
// dep). docChromeCSS shows exactly one per theme via the data-theme attribute.
const sunSVG = `<svg class="i-sun" viewBox="0 0 24 24" aria-hidden="true" focusable="false" ` +
	`fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round">` +
	`<circle cx="12" cy="12" r="4.1"/>` +
	`<path d="M12 2.6v2.1M12 19.3v2.1M2.6 12h2.1M19.3 12h2.1M5.1 5.1l1.5 1.5M17.4 17.4l1.5 1.5M18.9 5.1l-1.5 1.5M6.6 17.4l-1.5 1.5"/></svg>`

const moonSVG = `<svg class="i-moon" viewBox="0 0 24 24" aria-hidden="true" focusable="false" ` +
	`fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">` +
	`<path d="M20.5 14.3A8.2 8.2 0 0 1 9.7 3.5a8.2 8.2 0 1 0 10.8 10.8z"/></svg>`

// footerHTML renders the thin vanity footer, aligned to the text column. The
// link is operator-controlled (config, trusted) but still attribute-escaped. An
// empty link renders the wordmark unlinked.
func footerHTML(link string) string {
	mark := `<span class="mark">demiplane</span>`
	if link != "" {
		mark = `<a href="` + html.EscapeString(link) + `" rel="noopener noreferrer" class="mark">demiplane</a>`
	}
	return `<footer class="docfoot"><div class="wrap">Generated by ` + mark + "</div></footer>\n"
}

// replyBox renders the first-class inline reply box baked at the foot of a
// ?reply=question page, targeting slug's same-origin submit endpoint. Design
// invariants that make false success impossible:
//
//   - Absolute-path action (/answer/<slug>): the form posts to the content origin
//     that served the page — same-origin by construction, no cross-origin/mixed-
//     content failure, and correct once TLS lands (the scheme is inherited, not
//     hard-coded). The slug is attribute-escaped.
//   - No JavaScript: the browser navigates to the server's real response. The
//     "recorded" confirmation is server-rendered ONLY after the answer persists;
//     a failed write renders an honest error, never a success. Contrast the
//     dogfood incident's onsubmit timer that claimed success unconditionally.
//   - required textarea: a courtesy client-side guard; the server re-validates a
//     non-empty answer regardless.
//   - next (the ?next= publish param) rides along as a hidden field so the
//     server-rendered confirmation can flow the student to the follow-up lesson.
//     Hidden fields are client-tamperable, so the submit handler re-validates it;
//     it only ever produces a same-origin, slug-shaped link.
func replyBox(slug, next string) string {
	action := "/answer/" + html.EscapeString(slug)
	var nextField string
	if next != "" {
		nextField = `<input type="hidden" name="next" value="` + html.EscapeString(next) + `">` + "\n"
	}
	return `<section class="dp-reply" aria-labelledby="dp-reply-h">
<h2 id="dp-reply-h">Your answer</h2>
<form method="post" action="` + action + `">
` + nextField + `<textarea name="body" required placeholder="Your answer in your own words…"></textarea>
<div class="dp-reply-row"><button type="submit">Submit my answer</button></div>
</form>
<p class="dp-reply-note">Your answer posts to this server and is recorded before you see any confirmation.</p>
</section>
`
}

// replyBoxCSS styles the inline reply box using the shared theme tokens (with
// OKLCH fallbacks so it still renders under a --css override that ships no
// tokens), matching the editorial chrome. No layout property is transitioned.
const replyBoxCSS = `
.dp-reply{margin:2.6rem 0 0;padding:1.3rem 1.4rem;border:1px solid var(--line,oklch(0.895 0.008 255));
  border-radius:12px;background:var(--bg,oklch(0.972 0.004 250))}
.dp-reply h2{margin:0 0 .7rem;font-family:var(--serif);font-size:1.15rem;font-weight:600;
  letter-spacing:-.01em;border:none;padding:0;color:var(--ink,oklch(0.255 0.012 262))}
.dp-reply textarea{width:100%;min-height:7rem;font:inherit;padding:.7rem .8rem;box-sizing:border-box;
  border:1px solid var(--line,oklch(0.895 0.008 255));border-radius:8px;
  background:var(--bg,oklch(0.972 0.004 250));color:var(--ink,oklch(0.255 0.012 262));resize:vertical}
.dp-reply textarea:focus{outline:2px solid var(--accent,oklch(0.485 0.135 27));outline-offset:1px;border-color:transparent}
.dp-reply-row{display:flex;margin-top:.8rem}
.dp-reply button{font:inherit;font-weight:600;cursor:pointer;padding:.6rem 1.25rem;border:1px solid transparent;
  border-radius:8px;background:var(--accent,oklch(0.485 0.135 27));color:oklch(0.985 0.004 250)}
.dp-reply button:hover{filter:brightness(1.05)}
.dp-reply-note{margin:.75rem 0 0;font-size:.8rem;color:var(--muted,oklch(0.495 0.012 258))}
`

// Body renders src to inner HTML only (no <html>/<head> wrapper), so callers
// such as the /docs route can place it inside their own page chrome while
// reusing this single markdown engine.
func Body(src []byte) string {
	return renderBlocks(string(src))
}

// renderBlocks converts markdown block structure to HTML.
func renderBlocks(src string) string {
	lines := strings.Split(strings.ReplaceAll(src, "\r\n", "\n"), "\n")
	var out strings.Builder
	var para []string
	// used records the heading ids emitted so far in this document so colliding
	// slugs get a deterministic numeric suffix (uniqueSlug). Scoped per render, so
	// ids are stable for a given source and independent across documents.
	used := map[string]bool{}

	flushPara := func() {
		if len(para) == 0 {
			return
		}
		out.WriteString("<p>")
		out.WriteString(inline(strings.Join(para, " ")))
		out.WriteString("</p>\n")
		para = para[:0]
	}

	for i := 0; i < len(lines); i++ {
		line := lines[i]
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, "```"):
			flushPara()
			// The fence info-string names the language (```go); its first token
			// selects the syntax highlighter (highlight.go). Collect until close.
			lang := strings.TrimSpace(trimmed[3:])
			var code []string
			for i++; i < len(lines) && !strings.HasPrefix(strings.TrimSpace(lines[i]), "```"); i++ {
				code = append(code, lines[i])
			}
			joined := strings.Join(code, "\n")
			out.WriteString("<pre><code")
			if canon := canonLang(lang); canon != "" {
				out.WriteString(` class="language-` + canon + `"`)
			}
			out.WriteString(">")
			// highlight() escapes every byte it emits (classed span or plain run);
			// an unsupported language returns the source HTML-escaped and unstyled,
			// so the raw-HTML-in-code XSS guard holds either way.
			out.WriteString(highlight(lang, joined))
			out.WriteString("</code></pre>\n")

		case trimmed == "":
			flushPara()

		case reHRule.MatchString(trimmed):
			flushPara()
			out.WriteString("<hr>\n")

		case reHeading.MatchString(trimmed):
			flushPara()
			m := reHeading.FindStringSubmatch(trimmed)
			level := len(m[1])
			plain := headingText(m[2])
			id := uniqueSlug(plain, used)
			lvl := byte('0' + level)
			out.WriteString("<h")
			out.WriteByte(lvl)
			out.WriteString(` id="` + id + `">`)
			out.WriteString(inline(m[2]))
			out.WriteString(headingAnchor(id, plain))
			out.WriteString("</h")
			out.WriteByte(lvl)
			out.WriteString(">\n")

		case strings.HasPrefix(trimmed, "> "):
			flushPara()
			var quote []string
			for i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "> ") {
				quote = append(quote, strings.TrimPrefix(strings.TrimSpace(lines[i]), "> "))
				i++
			}
			i--
			out.WriteString("<blockquote>")
			out.WriteString(inline(strings.Join(quote, " ")))
			out.WriteString("</blockquote>\n")

		case isUnordered(trimmed) || reOrdered.MatchString(trimmed):
			flushPara()
			listHTML, next := renderList(lines, i)
			out.WriteString(listHTML)
			i = next - 1

		case strings.Contains(trimmed, "|") && i+1 < len(lines) && reTableSep.MatchString(lines[i+1]):
			// GFM pipe table: header row, |---| separator, then body rows until a
			// blank or non-pipe line.
			flushPara()
			header := splitCells(trimmed)
			i += 2 // consume header + separator; i now at the first body row
			var rows [][]string
			for i < len(lines) {
				lt := strings.TrimSpace(lines[i])
				if lt == "" || !strings.Contains(lt, "|") {
					break
				}
				rows = append(rows, splitCells(lt))
				i++
			}
			i-- // the outer loop's i++ advances past the last consumed row
			out.WriteString(renderTable(header, rows))

		default:
			para = append(para, trimmed)
		}
	}
	flushPara()
	return out.String()
}

func isUnordered(s string) bool {
	return strings.HasPrefix(s, "- ") || strings.HasPrefix(s, "* ") || strings.HasPrefix(s, "+ ")
}

// renderList consumes a contiguous run of list items starting at lines[start]
// and renders it to nested <ul>/<ol> HTML, returning the index of the first line
// past the list. A list run is the maximal block of consecutive non-blank lines
// whose trimmed form is an ordered (`1. `) or unordered (`- `/`* `/`+ `) item; a
// blank or non-item line ends it (matching the flat behavior it replaces).
//
// Nesting is driven by leading indentation (the house convention is two spaces
// per level, but any consistent widening nests and any narrowing closes, so
// deeper or ragged indentation still yields a valid tree). Ordered and unordered
// items mix freely: a change of marker kind at the same indent closes the current
// list and opens the other. Item text runs through inline(), which HTML-escapes
// before formatting, so the escape-first XSS posture is unchanged.
//
// Invariant: each open list frame always has exactly one <li> whose </li> is
// deferred until a sibling replaces it, a child list closes above it, or the run
// unwinds — which is what lets a nested list live inside its parent's still-open
// <li>.
func renderList(lines []string, start int) (string, int) {
	type frame struct {
		indent  int
		ordered bool
	}
	var b strings.Builder
	var stack []frame

	openTag := func(ordered bool) {
		if ordered {
			b.WriteString("<ol>\n")
		} else {
			b.WriteString("<ul>\n")
		}
	}
	closeTag := func(ordered bool) {
		if ordered {
			b.WriteString("</ol>\n")
		} else {
			b.WriteString("</ul>\n")
		}
	}

	i := start
	for i < len(lines) {
		raw := lines[i]
		trimmed := strings.TrimSpace(raw)
		ordered := reOrdered.MatchString(trimmed)
		unordered := isUnordered(trimmed)
		if !ordered && !unordered {
			break
		}
		indent := len(raw) - len(strings.TrimLeft(raw, " \t"))
		var content string
		if ordered {
			content = reOrdered.FindStringSubmatch(trimmed)[1]
		} else {
			content = trimmed[2:]
		}

		// Ascend: close every level deeper than this item's indent. Each pop closes
		// that level's open <li> and its list tag; the parent <li> it lived inside is
		// closed by the next shallower iteration (or by the sibling/unwind below).
		for len(stack) > 0 && indent < stack[len(stack)-1].indent {
			b.WriteString("</li>\n")
			closeTag(stack[len(stack)-1].ordered)
			stack = stack[:len(stack)-1]
		}

		if len(stack) > 0 && indent == stack[len(stack)-1].indent {
			// Sibling at the same level: close the previous item, then reopen as the
			// other marker kind if this item switched ordered<->unordered.
			b.WriteString("</li>\n")
			if stack[len(stack)-1].ordered != ordered {
				closeTag(stack[len(stack)-1].ordered)
				stack = stack[:len(stack)-1]
				openTag(ordered)
				stack = append(stack, frame{indent: indent, ordered: ordered})
			}
		} else {
			// Deeper than the current top (or the very first item): open a new list.
			// When deeper, it nests inside the parent's still-open <li>.
			openTag(ordered)
			stack = append(stack, frame{indent: indent, ordered: ordered})
		}

		b.WriteString("<li>")
		b.WriteString(inline(content))
		i++
	}

	// Unwind any levels left open at the end of the run.
	for len(stack) > 0 {
		b.WriteString("</li>\n")
		closeTag(stack[len(stack)-1].ordered)
		stack = stack[:len(stack)-1]
	}
	return b.String(), i
}

// splitCells splits a GFM table row into inline-rendered cell HTML. Leading and
// trailing pipes are stripped; each cell goes through inline(), which escapes
// before formatting — so cell content (including raw HTML) cannot inject.
func splitCells(row string) []string {
	s := strings.TrimSpace(row)
	s = strings.TrimPrefix(s, "|")
	s = strings.TrimSuffix(s, "|")
	parts := strings.Split(s, "|")
	cells := make([]string, len(parts))
	for i, p := range parts {
		cells[i] = inline(strings.TrimSpace(p))
	}
	return cells
}

// renderTable emits a <table> from a header and body rows of already-escaped,
// inline-rendered cell HTML. Rows are padded/truncated to the header width. The
// table is wrapped in a .table-wrap container that scrolls horizontally on its
// own (overflow-x:auto), so a table wider than the text measure scrolls inside
// its box instead of forcing the whole document body to scroll sideways on
// mobile.
func renderTable(header []string, rows [][]string) string {
	var b strings.Builder
	b.WriteString(`<div class="table-wrap">` + "\n")
	b.WriteString("<table>\n<thead><tr>")
	for _, h := range header {
		b.WriteString("<th>" + h + "</th>")
	}
	b.WriteString("</tr></thead>\n<tbody>\n")
	for _, r := range rows {
		b.WriteString("<tr>")
		for c := range header {
			cell := ""
			if c < len(r) {
				cell = r[c]
			}
			b.WriteString("<td>" + cell + "</td>")
		}
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody>\n</table>\n")
	b.WriteString("</div>\n")
	return b.String()
}

// inline escapes text and applies inline formatting. Escaping happens first so
// raw HTML in the source is rendered as text, never executed.
func inline(s string) string {
	s = html.EscapeString(s)
	s = reCode.ReplaceAllString(s, "<code>$1</code>")
	s = reLink.ReplaceAllStringFunc(s, renderLink)
	s = reBold.ReplaceAllString(s, "<strong>$1</strong>")
	s = reItalic.ReplaceAllString(s, "<em>$1</em>")
	s = reItalicU.ReplaceAllString(s, "<em>$1</em>")
	return s
}

// renderLink turns [text](url) into an anchor. Two layers of XSS defense:
//
//  1. Both text and url reach here ALREADY HTML-escaped, because inline()
//     escapes the whole line before any inline regex runs. So a url like
//     `https://a"onmouseover="x` arrives as `https://a&#34;onmouseover=&#34;x`
//     and cannot break out of the href attribute; injected text is inert too.
//  2. The URL scheme is checked against an ALLOWLIST (below); anything that is
//     not an explicitly-permitted scheme or a relative reference is dropped to
//     plain text, so javascript:/data:/vbscript: and unknown schemes never
//     become a live href. Rendered markdown is served same-origin, so this
//     matters.
func renderLink(match string) string {
	m := reLink.FindStringSubmatch(match)
	text, u := m[1], m[2]
	if !safeURL(u) {
		return text
	}
	return `<a href="` + u + `" rel="noopener noreferrer">` + text + `</a>`
}

// safeURL is an allowlist: it permits http/https/mailto absolute URLs and
// relative references (path, fragment, query), and rejects everything else —
// notably any other scheme. The input is already HTML-escaped; scheme tokens
// (http, https, mailto) contain no escapable characters, so prefix checks are
// reliable.
func safeURL(u string) bool {
	lu := strings.ToLower(strings.TrimSpace(u))
	if lu == "" {
		return false
	}
	if strings.HasPrefix(lu, "http://") || strings.HasPrefix(lu, "https://") || strings.HasPrefix(lu, "mailto:") {
		return true
	}
	// Protocol-relative URLs ("//host/path") are external navigations, not
	// same-origin relative refs — reject them so a published markdown link cannot
	// silently redirect off-site (open-redirect / phishing). Must precede the
	// single-"/" relative allow below, which would otherwise match "//".
	if strings.HasPrefix(lu, "//") {
		return false
	}
	// Relative references are safe: they cannot carry an active-content scheme.
	if strings.HasPrefix(lu, "/") || strings.HasPrefix(lu, "#") || strings.HasPrefix(lu, "?") {
		return true
	}
	// Bare relative path (e.g. "page.html", "sub/page"): allow only if there is
	// no scheme-like colon before the first path separator.
	if colon := strings.IndexByte(lu, ':'); colon >= 0 {
		sep := strings.IndexAny(lu, "/#?")
		if sep == -1 || colon < sep {
			return false // looks like "scheme:..." → reject
		}
	}
	return true
}

// docHead returns the document head with css inlined and the initial data-theme
// set on <html>. When toggle is true a tiny inline script runs before the body
// paints, resolving the viewer's theme (localStorage → server default →
// prefers-color-scheme) with no flash of the wrong theme.
func docHead(css, titleText, themeName string, toggle bool) string {
	initial := themeName
	if initial == "" {
		initial = theme.Default
	}
	if titleText == "" {
		titleText = "Untitled"
	}
	head := `<!DOCTYPE html>
<html lang="en" data-theme="` + initial + `">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="` + theme.MetaColor(initial) + `">
<title>` + titleText + `</title>
<style>` + css + `</style>
`
	if toggle {
		head += initThemeScript(themeName) + "\n"
	}
	return head + `</head>
<body>
`
}

// initThemeScript runs synchronously in <head> to set data-theme before paint.
// serverTheme is "" / "light" / "dark" (validated upstream), so embedding it in
// the JS string literal is injection-safe. Empty serverTheme means "no server
// default" → fall through to prefers-color-scheme.
func initThemeScript(serverTheme string) string {
	return `<script>(function(){try{var k='demiplane-theme',s=localStorage.getItem(k),d='` +
		serverTheme + `';var t=s||d||((window.matchMedia&&` +
		`matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light');` +
		`document.documentElement.setAttribute('data-theme',t);}catch(e){}})();</script>`
}

// docChromeScript wires the masthead's theme toggle (persisting the choice in
// localStorage) and the hairline + shadow on scroll. It runs after the body
// parses. The icon swap (sun/moon) is pure CSS keyed off data-theme.
const docChromeScript = `<script>(function(){
var k='demiplane-theme',btn=document.querySelector('.themetoggle');
if(btn){
var sync=function(){btn.setAttribute('aria-pressed',
document.documentElement.getAttribute('data-theme')==='dark'?'true':'false');};
sync();
btn.addEventListener('click',function(){
var cur=document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light';
var next=cur==='dark'?'light':'dark';
document.documentElement.setAttribute('data-theme',next);
sync();
try{localStorage.setItem(k,next);}catch(e){}});}
var bar=document.querySelector('.docbar');
if(bar){var f=function(){bar.classList.toggle('scrolled',window.scrollY>4);};f();
window.addEventListener('scroll',f,{passive:true});}
})();</script>
`

// docChromeCSS styles the sticky editorial masthead, the document measure, the
// quiet lead paragraph, and the thin vanity footer. Colors are theme tokens
// (with OKLCH fallbacks matching the current rojo palette so the chrome still
// renders if a --css override ships no tokens). The masthead carries no border
// until scrolled, then a hairline plus a soft shadow fade in on an ease-out-expo
// curve. Motion respects prefers-reduced-motion. Layout properties are never
// transitioned.
//
// The .doctitle single-line ellipsis truncation (white-space:nowrap;
// overflow:hidden;text-overflow:ellipsis) is DELIBERATE on the wide masthead: it
// is a fixed single-row bar, so a very long title clips to one line rather than
// wrapping and shoving the toggle out of the row. On narrow screens (<=34rem),
// where a one-line clip loses most of a long title, a mobile-only override
// (demiplane-ycd) relaxes to a 2-line -webkit-line-clamp: the title can grow to
// two lines and only then ellipsizes, while the flex toggle keeps its own row.
// The full title is always in <head><title> and, when the body keeps its H1, in
// the document body.
const docChromeCSS = `
main.wrap,.docbar>.wrap,.docfoot>.wrap{max-width:43rem}
main.wrap{padding-top:2.6rem}
.lead{font-size:1.2rem;line-height:1.62;color:var(--muted,oklch(0.495 0.012 258));
  font-weight:400;margin:0 0 1.7em}
.lead strong{color:var(--ink,oklch(0.255 0.012 262));font-weight:600}
.docbar{position:sticky;top:0;z-index:10;background:var(--bg,oklch(0.972 0.004 250));
  border-bottom:1px solid transparent;
  transition:border-color .35s cubic-bezier(.22,1,.36,1),box-shadow .35s cubic-bezier(.22,1,.36,1)}
.docbar.scrolled{border-bottom-color:var(--line,oklch(0.895 0.008 255));
  box-shadow:0 8px 24px -14px var(--shadow,oklch(0.280 0.010 262 / 0.14))}
.docbar>.wrap{display:flex;align-items:center;gap:1rem;padding-top:1.15rem;padding-bottom:1.05rem}
.docbar .masthead{display:flex;flex-direction:column;gap:.22rem;min-width:0}
.docbar .kicker{font-family:var(--sans);font-size:.7rem;font-weight:700;letter-spacing:.2em;
  text-transform:uppercase;color:var(--accent,oklch(0.485 0.135 27))}
.docbar .doctitle{font-family:var(--serif);font-size:1.5rem;font-weight:600;margin:0;
  line-height:1.3;letter-spacing:-.018em;border:none;padding:0 0 .14em;color:var(--ink,oklch(0.255 0.012 262));
  white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
@media (max-width:34rem){.docbar .doctitle{white-space:normal;overflow:hidden;
  display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;line-clamp:2}}
.themetoggle{margin-left:auto;flex:0 0 auto;display:inline-flex;align-items:center;justify-content:center;
  width:2.15rem;height:2.15rem;cursor:pointer;color:var(--muted,oklch(0.495 0.012 258));
  background:transparent;border:1px solid var(--line,oklch(0.895 0.008 255));border-radius:999px;
  transition:color .25s cubic-bezier(.22,1,.36,1),border-color .25s cubic-bezier(.22,1,.36,1)}
.themetoggle:hover{color:var(--accent,oklch(0.485 0.135 27));border-color:var(--accent,oklch(0.485 0.135 27))}
.themetoggle svg{width:1.05rem;height:1.05rem;display:block;
  transition:transform .35s cubic-bezier(.22,1,.36,1)}
.themetoggle:hover svg{transform:rotate(11deg) scale(1.06)}
.themetoggle .i-moon{display:none}
html[data-theme="dark"] .themetoggle .i-sun{display:none}
html[data-theme="dark"] .themetoggle .i-moon{display:block}
.docfoot{border-top:1px solid var(--line,oklch(0.895 0.008 255));margin-top:3rem}
.docfoot>.wrap{padding-top:.85rem;padding-bottom:.85rem;color:var(--muted,oklch(0.495 0.012 258));
  font-size:.76rem;letter-spacing:.01em}
.docfoot .mark{font-family:var(--serif);color:var(--accent,oklch(0.485 0.135 27));text-decoration:none}
.docfoot a.mark:hover{text-decoration:underline;text-underline-offset:2px}
@media (prefers-reduced-motion:reduce){
.docbar,.themetoggle,.themetoggle svg{transition:none}
.themetoggle:hover svg{transform:none}}
`

// printCSS makes a rendered artifact survive Cmd+P (demiplane-rwj item 5). A
// published document is meant to read like "a well-set private document", so the
// print sheet forces a page-friendly light palette regardless of the on-screen
// theme (dark and the pinned developer palettes waste toner and read poorly on
// paper), re-inverts the code slab to bordered-light, unsticks the masthead,
// hides interactive chrome (the theme toggle; heading anchors are already
// display:none in print via contentCSS), lets code wrap instead of clipping to a
// fixed scroll box, and sets sane @page margins. It overrides only the tokens the
// screen palette would otherwise darken; everything else inherits the same
// element typography, so the printed page is the screen document minus the
// screen. Ink is a near-black (not pure #000) to keep the house's no-pure-black
// spirit and spare toner; paper is the sheet's own white.
const printCSS = `
@media print{
  :root{
    --bg:#ffffff;--panel:#ffffff;--zebra:transparent;--ink:#1a1a1a;--muted:#565656;
    --line:#c9c9c9;--line-soft:#dddddd;--accent:#9a1b1b;--accent-hover:#9a1b1b;
    --accent-soft:#f2f2f2;--code-bg:#f6f6f4;--code-ink:#1f1f1f;--code-inline:#9a1b1b;
    --code-line:#c9c9c9;--shadow:transparent;
    --tok-key:#9a1b1b;--tok-fn:#1c5474;--tok-str:#1f6b3b;--tok-com:#6a6a6a;
  }
  html{scroll-padding-top:0}
  body{background:#ffffff;color:#1a1a1a;font-size:11pt;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  a{color:#1a1a1a;text-decoration:underline;text-underline-offset:2px}
  .docbar{position:static;box-shadow:none;border-bottom:1px solid #c9c9c9}
  .themetoggle{display:none}
  pre{background:#f6f6f4;color:#1f1f1f;border:1px solid #c9c9c9;
    white-space:pre-wrap;word-wrap:break-word;overflow:visible}
  pre code{color:inherit}
  blockquote{color:#1a1a1a}
  h2,h3{page-break-after:avoid}
  pre,blockquote,table,img{page-break-inside:avoid}
  .colo{page-break-inside:avoid}
  @page{margin:2cm}
}
`

const docTail = `</body>
</html>
`
